// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpklkjssynqixtbmrbfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwa2xranNzeW5xaXh0Ym1yYmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzEwNDUsImV4cCI6MjA1NjcwNzA0NX0.rTXFMCZq_lzg3pc-tO4HzL7NN4UjRHv9m03OxHx5jFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);